language: objective-c
osx_image: xcode8.3
rvm:
- 2.2
before_install:
- chmod a+x ./install.sh
- chmod a+x ./build.sh
install:
- ./install.sh
script:
- ./build.sh
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
#  file: "FILE TO UPLOAD"
  local-dir: Build
  skip_cleanup: true
  on:
    tags: true